### ISSUE TITLE
Message Controllers

### ISSUE THREAD

**Issue by Divlo** [Thream/api#6]
### Checklist

- [x] Tests
- [x] Docs
- [x] GET /channels/:channelId/messages - get all messages from a channel in ASC orders
- [x] POST /channels/:channelId/messages - realtime
- [x] PUT  /messages/:messageId - realtime
- [x] DELETE /messages/:messageId - realtime

**Comment by christophe-riolo** [comment]
I could work on this, however the semantics could be better defined.
GET -> get all the messages in ascending (time) order :heavy_check_mark: 
POST -> create a new message in the channel :heavy_check_mark: 
But PUT and DELETE are not obvious to me. Do you wish to replace all messages in a channel ? Or delete all messages in a channel ? or should it be:
PUT/DELETE /messages/:channelId/message/:messageId

Moreover I have one suggestion of change for the URL:
/channels/:channelId/messages.

**Comment by Divlo** [comment]
Alright @christophe-riolo !
When I'm talking about PUT and DELETE, it's about **one** single message.
So delete one specific message with its id.

If we change the url we need to also change the architecture of files, I want to have everything related to message in `/messages` and in `/src/controllers/Messages`, it looks clearer, what do you think ?

Because if we do `/channels/:channelId/messages`, the logic is to put controllers files inside the `/src/controllers/Channels` folder but this folder will be really big. Even if `messages` are related to channels, we might still need to separate concern.

**Comment by christophe-riolo** [comment]
From a pure REST perspective it would be better. As for the file organisation is it a matter of best practices or is that structure imposed ? I would see two options if we have a bit of freedom:
- use `/src/controllers/Messages` anyway even if we have `channels` higher in the path. The essential being to have some logic in our folder organisation.
- use `/src/controllers/Channels/Messages` so `/src/controllers/Channels` itself does not get too crowded. Deeper paths are not that messy.

What do you think ?

**Comment by Divlo** [comment]
For the file organization, we're free to do what we want, when I started the project (3 months ago) alone, I imagined that structure of files but as there are not that much things done, we could change that structure.

For the moment, we have 3 folders of controllers (always in `/src/controllers`) :
- `Channels`
- `Guilds`

**Comment by Divlo** [comment]
Right, for the file organization, we're free to do what we want, but we should stay consistent so if it's needed to change, we would need to change everywhere when needed in the current state of the project. As you said : 
> The essential being to have some logic in our folder organisation.

For the moment, we have 3 folders of controllers (always in `/src/controllers`) :
- `Channels` (we're using paths like that : `/channels/guilds/:guildId`)
- `Guilds`
- `Users` (don't need to change)

The thing is: I should be able to see the path and immediatly know what is the file in the code to handle that route logic.
Example: GET `/guilds`, the file is `/src/controllers/Guilds/get.ts`.

Actually, I quite like the second option :
> use `/src/controllers/Channels/Messages` so `/src/controllers/Channels` itself does not get too crowded. Deeper paths are not that messy.

I don't remember why I captilazed the names but in the path it's always small caps, for that matter we should also name the folders like it is in the path.
Example : `/guilds`, the file would be `/src/controllers/guilds/get.ts`.

If you think it is a good option to change the file structure like you said in the second option, maybe you could do the pull request with those changes as well.
